### ISSUE TITLE
Blank lines are inserted. Editor never released.

### ISSUE THREAD

**Issue by jidanni** [rosmanov/chrome-bee#8] opened 2023-03-10 06:08 UTC
I followed https://github.com/rosmanov/chrome-bee/wiki/Configuration-in-Chrome:
![20230310T140512](https://user-images.githubusercontent.com/1230959/224236671-3082d16f-1bc5-483d-9c41-d8ccb1948f57.jpg)
![20230310T142840](https://user-images.githubusercontent.com/1230959/224240588-62e51b92-6940-437e-81c8-a289a8c8df86.jpg)

OK, editing a file on https://commons.wikimedia.org/ , before I hit CTRL+E it looks like:
![20230310T140314](https://user-images.githubusercontent.com/1230959/224236760-4db0a93e-abc3-46ac-833c-79e5bc618c74.jpg)
Upon hitting CTRL+E it just becomes interspersed with blank lines, and read-only:
![20230310T140404](https://user-images.githubusercontent.com/1230959/224236790-50e5ebac-44ce-43a9-bf63-8b3e85740b13.jpg)

OK. Be sure to remind people at the bottom of
https://github.com/rosmanov/chrome-bee/wiki/Configuration-in-Chrome
that there is one more step needed (install the .deb etc.)!

OK, now the editor works, but the blank lines are still there. 
(I suppose maybe you are guessing the person is using a CRLF computer, but we are just using Linux LFs?)
And when we are finished editing the textbox is still readonly, meaning you haven't got the signal from the editor that it is finished.

Tested on Debian Sid.

**Comment by rosmanov** [comment] 2023-03-10 07:50
> OK. Be sure to remind people at the bottom of
> https://github.com/rosmanov/chrome-bee/wiki/Configuration-in-Chrome
> that there is one more step needed (install the .deb etc.)!

I thought people usually read the main README.md first. But I was wrong.

Added a note at the top of  the page:
> :warning:  **Please note that the browser extension will not work without the host application being [installed](https://github.com/rosmanov/chrome-bee#host-application).**

----

> OK, now the editor works, but the blank lines are still there.
> (I suppose maybe you are guessing the person is using a CRLF computer, but we are just using Linux LFs?)

There is no intended intervention to the text processing on beectl side. The application just reads content from the browser and passes it through to a temporary file. Then the file is opened with the editor binary as `{editor-command} {temporary-file}`.

As a first step, I tried to reproduce this issue on Fedora Linux(as I think there should be a big difference with Debian, actually) with gvim, and it worked without issues:
<video src="https://user-images.githubusercontent.com/608192/224254462-e8d243b0-6b00-4951-a941-3975b515d426.webm" controls="controls" style="max-width: 730px;"></video>

Do you think your editor could convert newlines to CRLF? I'm not familiar with emacs, sorry. Did you try using a simple editor for a test?

I guess, the page you tried to edit might contain CRLF line endings that might be not apparent on the web page. What if you just copy the textarea content and paste it into the editor using just the clipboard, will the line endings look correct?

Thanks.

**Comment by jidanni** [comment] 2023-03-11 02:28
What was probably going on is interference from the website:
https://github.com/fregante/GhostText/issues/249

Anyway I didn't test further because they have emacs ELPA, so i ended up using theirs. 

Also about reminding people: you might also want to warn even one futhther time in the bottom of the file too,  not just the top, for us with extra short memories :-)

**Comment by rosmanov** [comment] 2023-03-11 04:15
👌 Yes, it might be due to some “mode” on the website. I’m closing the issue then.

**Closed by rosmanov** 2023-03-11 04:15 UTC
Labels: bug
